---
version: 2
jobs:
  build:
    working_directory: /root/avrolixr

    docker:
      - image: avvo/elixir-circleci:1.4.1-4

    environment:
      MIX_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: avrolixr-{{ .Branch }}
          key: avrolixr-master

      - run: mix do deps.get, deps.compile, compile

      - save_cache:
          key: avrolixr-{{ .Branch }}
          key: avrolixr-master
          paths:
            - _build
            - deps

      - run:
          name: Run Tests
          command: mix test

      - store_test_results:
          path: /root/avrolixr/_build/test/lib/
